Awesome branch
RoyJumah/Awesome-Books pull request #1
Opened 2022-11-28 15:47 UTC by RoyJumah

2022-11-28 19:21 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hi @RoyJumah  and @lugard1 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️Readme
✔️Linters
✔️Github Flow
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-28 19:21 UTC, tugsem commented on script.js
> +}
- [ ] Please fix these console log errors occuring when the page loads. That's because there are no library array in local storage if you haven't set that first.
![image](https://user-images.githubusercontent.com/91486791/204359125-cbcd6e31-622c-4c95-bb72-f5e1dd8d4742.png)

2022-11-28 19:21 UTC, tugsem commented on script.js
> +  idBook += 1;
- [ ] Please assign the right ids to objects as it gives only zero to newly created items: 
![image](https://user-images.githubusercontent.com/91486791/204362385-129f8b30-d995-4b2a-9099-6af07708a4cb.png)

2022-11-28 19:21 UTC, tugsem commented on script.js
> +}
- [ ] As every item gets the same id number, this method deletes all of the storage which is not a good functionality. Kindly, fix this.

2022-11-28 20:04 UTC, RoyJumah commented on script.js
> +}
@tugsem Could you please clarify on this error, I can't see this error message on my end

2022-11-28 20:33 UTC, RoyJumah commented on script.js
> +  idBook += 1;
@tugsem And also in for this, in my end each object new object get a unique id
![image](https://user-images.githubusercontent.com/61903079/204375207-2fa54d16-1bba-4584-a48e-4c04863858b3.png)

2022-11-29 05:12 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi Team,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-29 05:15 UTC, merged